name: Run Unit Test and push to AWS

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: restore dependencies
        run: dotnet restore

      - name: Run Unit Tests
        run: dotnet test

      - name: Upload test results to S3
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet restore; dotnet publish -o morse;

      - name: Create zip package
        run: cd morse; zip ../morse.zip *;

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.MORSE_API_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.MORSE_API_SECRET_KEY }}
          application_name: Morse API 
          environment_name: MorseAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: morse.zip